version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "merge"
      - "dependencies"

  # Configuration for NuGet
 # - package-ecosystem: "nuget"
 #   directory: "/"
 #   schedule:
 #     interval: "daily"
 #   labels:
 #     - "automerge"
 #     - "dependencies"
