name: Dependabot auto-merge

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.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 }}"

      - name: Verify Dependabot
        run: |
          if [[ "${{ github.event.sender.type }}" != "Bot" || "${{ github.event.sender.login }}" != "dependabot[bot]" ]]; then
            echo "This PR is not from Dependabot."
            exit 1
          fi

      - name: Enable auto-merge for Dependabot PRs
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.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 }}